name: cron

on:
  schedule:
    - cron: '59 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Main
        run: |
          CODE=`curl ${{ secrets.CURL_ARGS }}${{ secrets.GITHUB_TOKEN }}`
          echo ""
          printf "$CODE"
          echo ""
          if [[ "$CODE" =~ ^ERROR ]] || [[ "$CODE" = "" ]]; then
            exit 1
          fi
