name: cron

on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Main
        run: |
          CODE=`curl -H '${{ secrets.TOKEN }}:${{ secrets.GITHUB_TOKEN }}' ${{ secrets.CURL_ARGS }}`
          echo ""
          printf "$CODE"
          echo ""
          if [[ "$CODE" =~ ^ERROR ]]; then
            exit 1
          fi
